### ISSUE TITLE
UI Policy doesn’t hide container variables

### ISSUE THREAD

**Issue by dpm566** [service-portal/documentation#80]
In the platform UI, UI Policy set on the container variables hides all its variables but the UI Policy breaks in Service Portal.

**Comment by zzjasonzz** [comment]
Make sure your policies are set with a UI type of both or mobile for service portal.   We've also been using script to hide some of our variables until polices are fixed in the portal.

**Comment by dpm566** [comment]
I have already set it to both. The UI Policies on variable type other than containers seems to work fine, its just the policies on container variables which breaks.

**Comment by t1mb0b** [comment]
I am having the same issue; I have a ticket open with HI on this.

**Comment by t1mb0b** [comment]
This is realted to PRB690516; fixed in HP4:

_When there is one UI policy that is meant to "hide" a container with its variables, and there is a second UI policy where if it sees the value of a certain variable within the container, it will show a different variable in that container. It breaks by showing the container and some of the variables inside, even though it is supposed to be hidden. This issue occurs after upgrading from Geneva or Helsinki instances to Helsinki Patch 1._

**Comment by t1mb0b** [comment]
Upgraded to Patch 4; does not seem the issue has been resolved :(

**Comment by JeffSalisbury** [comment]
Patch 4 has also not resolved hiding cascading variables in an Order Guide.

**Comment by iamwill** [comment]
This is coming in HP5. You will be able to use setDisplay on variable sets using UI policy or g_form in a client script.
